env: "local"
storage_path: "./storage/storage.db"
db:
  address: "localhost:5432"
  user: "postgres"
  password: "postgres"
  database: "url_shortener_db"

http_server:
  address: "192.168.1.40:8080"
  timeout: 5s
  idle_timeout: 30s
  user: "admin" # password in env variable HTTP_SERVER_PASSWORD